#pragma once
enum AirborneTargetTypes
{
	TARGET_UNKNOWN = 0,
	TARGET_ATTACK,
	TARGET_AIRBORNE_SEARCH_RADAR,
	TARGET_EF_2000,
	TARGET_TORNADO,
	TARGET_PHANTOM,
	TARGET_F5_TIGER,
	TARGET_TOMCAT,
	TARGET_EAGLE,
	TARGET_FALCON,
	TARGET_HORNET,
	TARGET_MIRAGE_2000,
	TARGET_MIG_21,
	TARGET_MIG_23,
	TARGET_MIG_25,
	TARGET_MIG_29,
	TARGET_MIG_31,
	TARGET_RAPTOR,
	TARGET_COUNT
};

enum GroundThreatTypes
{
	THREAT_UNKNOWN = 100,
	THREAT_SA_2,
	THREAT_SA_3,
	THREAT_SA_4,
	THREAT_SA_5,
	THREAT_SA_6,
	THREAT_SA_8,
	THREAT_SA_10,
	THREAT_SA_11,
	THREAT_SA_15,
	THREAT_SA_17,
	THREAT_SA_19,
	THREAT_NIKE,
	THREAT_HAWK,
	THREAT_SEARCH,
	THREAT_HB_AAA,
	THREAT_LB_AAA,
	THREAT_AAA,
	THREAT_KSAM,
	THREAT_PATRIOT,
	THREAT_TOTAL
};

